#!/usr/bin/env python3
"""Build a public-safe evidence bundle that maps artifacts to claim boundaries."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from research_clock import utc_date_iso


DEFAULT_OUTPUT = "docs/results/sanitized-evidence-bundle-20260630.md"
DEFAULT_JSON_OUTPUT = "data/sanitized-evidence-bundle-20260630.json"


@dataclass(frozen=True)
class EvidenceItem:
    id: str
    chapter: str
    category: str
    implementation: str
    evidence_doc: str
    runner_or_tool: str
    local_artifact_id: str
    claim_strength: str
    supports: str
    do_not_claim: str
    next_gap: str


EVIDENCE_ITEMS = [
    EvidenceItem(
        id="quic-go-active-migration-positive-control",
        chapter="3",
        category="implementation-positive-control",
        implementation="quic-go",
        evidence_doc="docs/results/quic-go-minimum-reproduction-results.md",
        runner_or_tool="harness/scripts/run-local-quic-go.sh",
        local_artifact_id="chapter3-local-quic-go-rerun-20260630",
        claim_strength="strong_local_positive",
        supports="Controlled AddPath/Probe/Switch active migration with qlog path validation and before/after payload continuity.",
        do_not_claim="Chrome, Safari, Android, CDN, or managed deployment handover success.",
        next_gap="Keep as transport positive control; browser and deployment evidence must stay separate.",
    ),
    EvidenceItem(
        id="cross-implementation-fresh-rerun",
        chapter="1",
        category="implementation-maturity",
        implementation="quiche, picoquic, s2n-quic, MsQuic, ngtcp2, aioquic, Quinn, Neqo",
        evidence_doc="docs/results/implementation-rerun-results-20260630.md",
        runner_or_tool="data/implementation-survey.csv",
        local_artifact_id="impl-rerun-20260630T070249Z",
        claim_strength="broad_test_suite",
        supports="Multiple QUIC stacks implement and test path validation, rebinding, migration, and related primitives.",
        do_not_claim="All implementations have identical app-level migration behavior or production deployment readiness.",
        next_gap="Promote selected source-only or partial candidates with focused runtime checks.",
    ),
    EvidenceItem(
        id="quiche-path-event-observability",
        chapter="1",
        category="implementation-observability",
        implementation="Cloudflare quiche",
        evidence_doc="docs/results/quiche-path-event-timeline-20260623.md",
        runner_or_tool="data/quiche-path-event-timeline.csv",
        local_artifact_id="quiche-local-success",
        claim_strength="observability_positive",
        supports="Path lifecycle can be observed with migration/path validation events and qlog-compatible evidence.",
        do_not_claim="Cloudflare managed edge or browser handover semantics.",
        next_gap="Use as lifecycle vocabulary baseline, not as CDN deployment evidence.",
    ),
    EvidenceItem(
        id="lsquic-preferred-address-app-demo",
        chapter="1",
        category="implementation-app-demo",
        implementation="LiteSpeed LSQUIC",
        evidence_doc="docs/results/lsquic-preferred-address-app-demo-20260630.md",
        runner_or_tool="harness/scripts/run-lsquic-preferred-address-demo.sh",
        local_artifact_id="lsquic-preferred-address-script-20260630T095500Z",
        claim_strength="app_level_positive",
        supports="LSQUIC example HTTP/3 client/server completed an app workload with preferred-address path transition evidence.",
        do_not_claim="OpenLiteSpeed production server success.",
        next_gap="Run production-like OpenLiteSpeed server demo on Linux or EC2.",
    ),
    EvidenceItem(
        id="lsquic-nat-rebinding-app-demo",
        chapter="1",
        category="implementation-app-demo",
        implementation="LiteSpeed LSQUIC",
        evidence_doc="docs/results/lsquic-nat-rebinding-app-demo-20260630.md",
        runner_or_tool="harness/scripts/run-lsquic-nat-rebinding-demo.sh",
        local_artifact_id="lsquic-nat-rebinding-demo-20260630T102751Z",
        claim_strength="app_level_positive",
        supports="LSQUIC example HTTP/3 workload completed through local UDP proxy NAT rebinding with new-path validation evidence.",
        do_not_claim="Mobile handover or production OpenLiteSpeed continuity.",
        next_gap="Compare with production-like server integration.",
    ),
    EvidenceItem(
        id="quicly-focused-e2e-path-migration",
        chapter="1",
        category="implementation-focused-e2e",
        implementation="quicly",
        evidence_doc="docs/results/quicly-e2e-path-migration-20260630.md",
        runner_or_tool="harness/scripts/run-quicly-e2e-path-migration-check.sh",
        local_artifact_id="quicly-e2e-path-migration-local-20260630",
        claim_strength="focused_e2e_positive",
        supports="quicly `path-migration` e2e subtest passed, including CID sequence 1 first path probe check.",
        do_not_claim="Full quicly `t/e2e.t` success; the full e2e still fails an unrelated `slow-start` subtest on this host.",
        next_gap="Use Linux/upstream-compatible timing environment to check full e2e cleanliness.",
    ),
    EvidenceItem(
        id="nginx-active-client-migration-runtime",
        chapter="1",
        category="server-runtime-positive-control",
        implementation="nginx QUIC",
        evidence_doc="docs/results/nginx-quic-active-migration-runtime-20260630.md",
        runner_or_tool="harness/scripts/run-nginx-quic-active-migration-demo.sh",
        local_artifact_id="nginx-quic-active-migration-20260630T104724Z",
        claim_strength="server_runtime_positive",
        supports="nginx HTTP/3 server handled quiche active source-port migration and completed a 1MiB response.",
        do_not_claim="Browser handover, client active migration API, or Linux quic_bpf production routing success.",
        next_gap="Run Linux quic_bpf packet-routing deployment check.",
    ),
    EvidenceItem(
        id="haproxy-http3-negative-control",
        chapter="4",
        category="deployment-negative-control",
        implementation="HAProxy QUIC",
        evidence_doc="docs/results/haproxy-http3-negative-control-rerun-20260630.md",
        runner_or_tool="harness/scripts/run-haproxy-http3-negative-control.sh",
        local_artifact_id="haproxy-http3-negative-control-20260630T110201Z",
        claim_strength="negative_control",
        supports="HTTP/3 proxy availability is insufficient evidence of active Connection Migration support.",
        do_not_claim="All future HAProxy versions lack migration support.",
        next_gap="Keep as proxy termination boundary and version-scoped negative control.",
    ),
    EvidenceItem(
        id="nginx-quic-bpf-readiness",
        chapter="4",
        category="deployment-readiness",
        implementation="nginx QUIC",
        evidence_doc="docs/results/nginx-quic-bpf-readiness-20260630.md",
        runner_or_tool="harness/scripts/check-nginx-quic-bpf-readiness.sh",
        local_artifact_id="nginx-quic-bpf-readiness-local-20260630-commitcheck",
        claim_strength="readiness_blocked",
        supports="Current repo separates nginx local runtime evidence from Linux/eBPF quic_bpf production-routing claim.",
        do_not_claim="quic_bpf production deployment success on macOS.",
        next_gap="Rerun on Linux with suitable eBPF/root or capability setup.",
    ),
    EvidenceItem(
        id="nginx-quic-bpf-linux-runner",
        chapter="4",
        category="deployment-runtime-readiness",
        implementation="nginx QUIC",
        evidence_doc="docs/results/nginx-quic-bpf-linux-runner-20260630.md",
        runner_or_tool="harness/scripts/run-nginx-quic-bpf-linux-demo.sh",
        local_artifact_id="nginx-quic-bpf-linux-demo-local-blocked-20260630",
        claim_strength="readiness_blocked",
        supports="The repo has a Linux fail-closed runner that enables nginx `quic_bpf on;` with `listen ... reuseport` and reuses the active migration HTTP/3 workload when host gates are open.",
        do_not_claim="Linux/eBPF quic_bpf migration success on the current macOS host.",
        next_gap="Run the Linux runner on EC2 or another Linux host with root/capability and writable /sys/fs/bpf.",
    ),
    EvidenceItem(
        id="aws-nlb-cid-aware-positive-control",
        chapter="4",
        category="deployment-positive-control",
        implementation="AWS NLB + quic-go",
        evidence_doc="docs/results/aws-nlb-quic-data-plane-results-20260624.md",
        runner_or_tool="harness/scripts/run-aws-nlb-quic-data-plane.sh",
        local_artifact_id="aws-nlb-quic-data-plane-20260624",
        claim_strength="deployment_positive",
        supports="CID-aware NLB passthrough can preserve backend continuity when routable CID layout matches the load balancer contract.",
        do_not_claim="All AWS HTTP/3, CloudFront, or CDN paths preserve end-to-end Connection Migration.",
        next_gap="Repeat with s2n-quic backend once AWS credentials and dedicated runner are ready.",
    ),
    EvidenceItem(
        id="aws-nlb-negative-controls",
        chapter="4",
        category="deployment-negative-control",
        implementation="AWS NLB + malformed/mismatched CID",
        evidence_doc="docs/results/aws-nlb-quic-negative-control-results-20260624.md",
        runner_or_tool="harness/scripts/run-aws-nlb-quic-data-plane.sh",
        local_artifact_id="aws-nlb-cid-negative-20260624",
        claim_strength="negative_control",
        supports="Target health or QUIC listener support is not enough when CID layout or Server ID registration is wrong.",
        do_not_claim="NLB failure under valid routable CID configuration.",
        next_gap="Keep paired with NLB positive control in deployment chapter.",
    ),
    EvidenceItem(
        id="aws-nlb-http3-workload",
        chapter="4",
        category="deployment-application-bridge",
        implementation="AWS NLB + quic-go HTTP/3",
        evidence_doc="docs/results/aws-nlb-http3-workload-results-20260624.md",
        runner_or_tool="repro/quic-go-min-repro/cmd/h3client/main.go",
        local_artifact_id="aws-nlb-http3-workload-20260624",
        claim_strength="application_bridge_positive",
        supports="Transport-level NLB continuity can be extended to a controlled HTTP/3 before/after workload.",
        do_not_claim="Browser-level task continuity or service-worker recovery behavior.",
        next_gap="Compare with browser public-origin handover evidence when device/network setup is available.",
    ),
    EvidenceItem(
        id="s2n-nlb-cid-provider-proof",
        chapter="4",
        category="deployment-prerequisite",
        implementation="s2n-quic",
        evidence_doc="docs/results/s2n-quic-nlb-cid-provider-rerun-20260630.md",
        runner_or_tool="harness/scripts/run-local-s2n-nlb-cid-proof.sh",
        local_artifact_id="local-data-plane-20260630T101625Z",
        claim_strength="local_prerequisite_positive",
        supports="s2n-quic can use an AWS NLB-compatible plaintext CID provider in a local data-plane proof.",
        do_not_claim="Live AWS NLB+s2n target forwarding or active migration success.",
        next_gap="Run the dedicated live AWS NLB+s2n target A/B forwarding runner after credentials are refreshed.",
    ),
    EvidenceItem(
        id="s2n-nlb-live-readiness",
        chapter="4",
        category="deployment-readiness",
        implementation="AWS NLB + s2n-quic",
        evidence_doc="docs/results/s2n-nlb-live-readiness-20260630.md",
        runner_or_tool="harness/scripts/check-s2n-nlb-live-readiness.sh",
        local_artifact_id="s2n-nlb-live-readiness-after-runner-proof-20260630",
        claim_strength="readiness_blocked",
        supports="Current live AWS+s2n experiment is fail-closed because AWS identity is invalid; local proof and dedicated runner readiness are present.",
        do_not_claim="Live AWS resource creation or live s2n NLB migration evidence.",
        next_gap="Refresh AWS credentials and execute the dedicated s2n live NLB forwarding runner.",
    ),
    EvidenceItem(
        id="aws-s2n-nlb-live-runner",
        chapter="4",
        category="deployment-live-runner",
        implementation="AWS NLB + s2n-quic",
        evidence_doc="docs/results/aws-s2n-nlb-live-runner-20260630.md",
        runner_or_tool="harness/scripts/run-aws-s2n-nlb-live-data-plane.sh",
        local_artifact_id="aws-s2n-nlb-live-local-blocked-20260630",
        claim_strength="readiness_blocked",
        supports="The repo has a dedicated AWS NLB+s2n live runner with compiling server/client binaries, a local echo smoke, and a pre-resource AWS identity gate.",
        do_not_claim="Live AWS NLB forwarding success, active migration success, or browser handover.",
        next_gap="Refresh AWS credentials and run the live forwarding echo before designing an active path-change variant.",
    ),
    EvidenceItem(
        id="aws-s2n-live-runner-safety-audit",
        chapter="4",
        category="deployment-safety-audit",
        implementation="AWS NLB + s2n-quic",
        evidence_doc="docs/results/aws-s2n-live-runner-safety-audit-20260701.md",
        runner_or_tool="tools/audit_aws_s2n_live_runner_safety.py",
        local_artifact_id="aws-s2n-live-runner-safety-audit-20260701",
        claim_strength="safety_audit",
        supports="A static audit of the live AWS NLB+s2n runner's fail-closed identity gate, temporary resource inventory, cleanup coverage, and claim boundary before live resource creation.",
        do_not_claim="Live AWS forwarding success, active migration success, zero cost, or cleanup success under every possible process-kill/cloud-failure mode.",
        next_gap="After credentials are refreshed, run live forwarding echo with default cleanup and inspect the resulting summary before phase-2 active path-change design.",
    ),
    EvidenceItem(
        id="aws-s2n-phase2-path-change-design",
        chapter="4",
        category="deployment-experiment-design",
        implementation="AWS NLB + s2n-quic",
        evidence_doc="docs/results/aws-s2n-phase2-path-change-design-20260701.md",
        runner_or_tool="tools/build_aws_s2n_phase2_path_change_design.py",
        local_artifact_id="aws-s2n-phase2-path-change-design-20260701",
        claim_strength="experiment_design",
        supports="A phase-2 AWS NLB+s2n design that separates live forwarding echo, NAT-rebinding proxy continuity, Linux namespace/SNAT path-change, lower-level s2n test-IO rebind, and future public active API work.",
        do_not_claim="New runtime evidence, current upstream public active migration API support, live AWS forwarding success, or browser handover.",
        next_gap="Run forwarding echo after AWS credentials open; if it passes, execute the packaged NAT-rebinding proxy variant as passive/path-change continuity evidence.",
    ),
    EvidenceItem(
        id="aws-s2n-phase2-rebinding-runner-audit",
        chapter="4",
        category="deployment-runner-readiness",
        implementation="AWS NLB + s2n-quic",
        evidence_doc="docs/results/aws-s2n-phase2-rebinding-runner-audit-20260701.md",
        runner_or_tool="tools/audit_aws_s2n_phase2_rebinding_runner.py",
        local_artifact_id="aws-s2n-nlb-rebinding-proxy-preflight-20260701",
        claim_strength="runner_readiness_audit",
        supports="A packaged phase-2 NAT-rebinding proxy mode for the AWS NLB+s2n runner, with chunked client traffic, remote-safe UDP proxy binding, proxy-observed rebind classification, and fail-closed pre-resource gating.",
        do_not_claim="Live AWS NLB+s2n NAT-rebinding continuity, application-triggered active migration, browser handover, or current upstream s2n public active migration API support.",
        next_gap="After credentials open, run forwarding echo first; if it passes, run PATH_CHANGE_MODE=rebinding_proxy with chunked client traffic and inspect proxy/server/client artifacts.",
    ),
    EvidenceItem(
        id="aws-s2n-phase2-artifact-classifier-contract",
        chapter="4",
        category="deployment-artifact-classifier",
        implementation="AWS NLB + s2n-quic",
        evidence_doc="docs/results/aws-s2n-phase2-artifact-classifier-contract-20260701.md",
        runner_or_tool="tools/classify_aws_s2n_phase2_artifact.py",
        local_artifact_id="aws-s2n-phase2-artifact-classifier-contract-20260701",
        claim_strength="artifact_classifier_contract",
        supports="A strict classifier contract for future AWS NLB+s2n artifacts, separating forwarding echo prerequisite evidence from NAT-rebinding proxy continuity and requiring proxy B-side packets plus chunked client traffic for phase-2 acceptance.",
        do_not_claim="A future AWS artifact is positive without running this classifier, or that a phase-2 NAT-rebinding proxy PASS proves public s2n application-triggered active migration.",
        next_gap="After live artifacts exist, run this classifier with --require-accepted before converting AWS results into paper rows.",
    ),
    EvidenceItem(
        id="s2n-active-migration-api-audit",
        chapter="4",
        category="implementation-api-audit",
        implementation="s2n-quic",
        evidence_doc="docs/results/s2n-active-migration-api-audit-20260630.md",
        runner_or_tool="tools/audit_s2n_active_migration_feasibility.py",
        local_artifact_id="s2n-connection-migration-tests-20260630",
        claim_strength="source_test_audit",
        supports="s2n-quic has connection migration/rebinding tests and active-path observability, while the current public app API does not expose a quic-go-like AddPath/Probe/Switch trigger.",
        do_not_claim="AWS NLB+s2n active migration execution, public application-triggered active migration, or browser handover.",
        next_gap="Run live NLB forwarding echo after credential refresh, then design a lower-level active path-change variant or wait for a public API.",
    ),
    EvidenceItem(
        id="openlitespeed-runtime-runner",
        chapter="4",
        category="deployment-readiness",
        implementation="OpenLiteSpeed + LSQUIC",
        evidence_doc="docs/results/openlitespeed-active-migration-runner-20260630.md",
        runner_or_tool="harness/scripts/run-openlitespeed-active-migration-demo.sh",
        local_artifact_id="openlitespeed-active-migration-local-blocked-20260630",
        claim_strength="readiness_blocked",
        supports="The repo has a Linux/EC2 runner for a production-like OpenLiteSpeed active-migration demo and records the current macOS blocker.",
        do_not_claim="OpenLiteSpeed runtime CM success or failure.",
        next_gap="Run on Linux/EC2 with OpenLiteSpeed binary and sufficient disk.",
    ),
    EvidenceItem(
        id="mvfst-source-audit",
        chapter="1",
        category="source-audit",
        implementation="mvfst",
        evidence_doc="docs/results/mvfst-cm-source-audit-20260630.md",
        runner_or_tool="tools/scan_implementation_evidence.py",
        local_artifact_id="mvfst-source-audit-20260630",
        claim_strength="source_test_audit",
        supports="mvfst has dedicated path manager, client active migration flow, server passive migration state machine, qlog/stat hooks, and migration tests.",
        do_not_claim="Local mvfst build/test success.",
        next_gap="Run focused mvfst migration tests on Linux builder.",
    ),
    EvidenceItem(
        id="mvfst-migration-test-readiness",
        chapter="1",
        category="implementation-readiness",
        implementation="mvfst",
        evidence_doc="docs/results/mvfst-migration-test-readiness-20260630.md",
        runner_or_tool="tools/check_mvfst_migration_test_readiness.py",
        local_artifact_id="mvfst-migration-test-readiness-20260630",
        claim_strength="readiness_blocked",
        supports="mvfst latest HEAD has focused migration/path-manager test files, 106 observed test cases, and BUCK targets for path-manager, client active migration, and server passive migration coverage.",
        do_not_claim="Local mvfst build/test success or runtime migration behavior.",
        next_gap="Run BUCK focused targets or getdeps build/test on a Linux or sufficiently provisioned builder.",
    ),
    EvidenceItem(
        id="chromium-cronet-policy-evidence",
        chapter="5",
        category="browser-policy-source",
        implementation="Chromium/Cronet",
        evidence_doc="docs/results/chromium-cronet-source-evidence-20260624.md",
        runner_or_tool="tools/check_browser_cm_observability.py",
        local_artifact_id="chromium-cronet-source-evidence-20260624",
        claim_strength="source_policy_evidence",
        supports="Browser/client stack has migration hooks and NetLog events, but runtime policy controls whether migration occurs.",
        do_not_claim="Chrome or Cronet handover success from source hooks alone.",
        next_gap="Run real browser/network-change trial when non-iPhone path is ready.",
    ),
    EvidenceItem(
        id="safari-webdriver-session-readiness",
        chapter="5",
        category="browser-readiness",
        implementation="Safari desktop + safaridriver",
        evidence_doc="docs/results/safari-webdriver-session-readiness-20260630.md",
        runner_or_tool="tools/check_browser_cm_observability.py",
        local_artifact_id="safari-webdriver-local-smoke-20260630",
        claim_strength="readiness_blocked",
        supports="Safari and safaridriver binaries are present and packet-capture tooling is available, but real WebDriver session creation currently fails because Safari Allow remote automation is not enabled.",
        do_not_claim="Safari controlled-public baseline execution, Safari network-change execution, or Safari browser-internal QUIC session continuity.",
        next_gap="Enable Safari Allow remote automation, rerun session smoke, then run controlled-public Safari baseline.",
    ),
    EvidenceItem(
        id="user-provided-public-origin-readiness",
        chapter="7",
        category="public-origin-readiness",
        implementation="user-provided public HTTPS origin",
        evidence_doc="docs/results/user-provided-public-origin-readiness-20260630.md",
        runner_or_tool="tools/check_public_origin_readiness.py",
        local_artifact_id="user-provided-public-origin-readiness-20260630",
        claim_strength="readiness_blocked",
        supports="The user-provided public HTTPS origin is reachable over HTTPS but does not currently advertise `Alt-Svc: h3`, so it is not a ready controlled-public H3 target.",
        do_not_claim="Chrome controlled-public H3 baseline, browser Connection Migration, or usable public-origin workload continuity.",
        next_gap="Configure a controlled H3 origin with WebPKI TLS, Alt-Svc, and workload endpoints, then rerun readiness with `--require-h3-alt-svc`.",
    ),
    EvidenceItem(
        id="non-iphone-gate-rerun-20260701",
        chapter="7",
        category="cross-gate-readiness",
        implementation="AWS NLB+s2n, Safari desktop, user-provided public origin",
        evidence_doc="docs/results/non-iphone-gate-rerun-20260701.md",
        runner_or_tool="tools/build_non_iphone_gate_rerun_report.py",
        local_artifact_id="non-iphone-gate-rerun-20260701",
        claim_strength="readiness_blocked",
        supports="The current non-iPhone gates were rerun: AWS remains credential-blocked, Safari WebDriver session remains disabled, and the user-provided public origin remains non-H3-ready.",
        do_not_claim="AWS NLB live forwarding, Safari controlled-public execution, Chrome public-origin H3 baseline, or browser Connection Migration.",
        next_gap="Open one gate: refresh AWS credentials, configure a controlled H3 public origin, or enable Safari Allow remote automation.",
    ),
    EvidenceItem(
        id="controlled-public-chrome-bridge-synthesis",
        chapter="7-9",
        category="browser-deployment-bridge-synthesis",
        implementation="Chrome + controlled public quic-go H3",
        evidence_doc="docs/results/controlled-public-chrome-bridge-synthesis-20260701.md",
        runner_or_tool="tools/build_controlled_public_chrome_bridge_synthesis.py",
        local_artifact_id="tracked-controlled-public-chrome-validation-docs-20260629",
        claim_strength="bridge_gap_negative_controls",
        supports="Tracked controlled-public Chrome validation records include H3 no-change baselines and active network-change negative controls; none combine active network change, application continuity, tuple change, and QUIC path validation.",
        do_not_claim="Controlled-public Chrome single-session Connection Migration success, final browser handover success, or upload coverage from untracked local validation notes.",
        next_gap="Open a controlled public H3 origin and rerun page-ready media/range/upload trials with artifact-bundle validation.",
    ),
    EvidenceItem(
        id="controlled-public-chrome-artifact-classifier-contract",
        chapter="7-11",
        category="browser-artifact-classifier",
        implementation="Chrome + controlled public H3 workload artifacts",
        evidence_doc="docs/results/controlled-public-chrome-artifact-classifier-contract-20260701.md",
        runner_or_tool="tools/build_controlled_public_chrome_artifact_classifier_contract.py",
        local_artifact_id="controlled-public-chrome-artifact-classifier-contract-20260701",
        claim_strength="artifact_classifier_contract",
        supports="A strict public Chrome artifact contract that separates H3 baseline, no-change controls, application recovery/reconnect, negative controls, and strong single-session CM rows.",
        do_not_claim="A future public Chrome row is strong CM evidence without application completion, client active path change, target tuple change, qlog path validation, and exactly one Chrome target QUIC session in the same row.",
        next_gap="After public-origin and desktop path gates open, run the source classifier on each row and apply this contract before converting results into paper claims.",
    ),
    EvidenceItem(
        id="controlled-public-chrome-contract-application-audit",
        chapter="7-11",
        category="browser-claim-audit",
        implementation="Chrome + tracked controlled public H3 rows",
        evidence_doc="docs/results/controlled-public-chrome-contract-application-audit-20260701.md",
        runner_or_tool="tools/build_controlled_public_chrome_contract_application_audit.py",
        local_artifact_id="controlled-public-chrome-contract-application-audit-20260701",
        claim_strength="claim_boundary_audit",
        supports="Applying the Chrome artifact contract to the tracked bridge rows yields public H3 baselines, task-completion-without-CM rows, and negative/gap records, with zero strong single-session CM rows.",
        do_not_claim="The two active application-completion rows prove browser Connection Migration; they still miss qlog path validation and Chrome single-session evidence.",
        next_gap="Use this audit as the public Chrome claim ledger until new rows pass the source classifier and contract.",
    ),
    EvidenceItem(
        id="chrome-local-rebinding-workload-controls",
        chapter="6",
        category="browser-local-control",
        implementation="Chrome + quic-go local UDP rebinding proxy",
        evidence_doc="docs/results/workload-sensitivity-synthesis-20260629.md",
        runner_or_tool="repro/quic-go-min-repro/scripts/run-chrome-h3-rebinding-proxy.sh",
        local_artifact_id="chrome-h3-rebinding-20260624-20260629-series",
        claim_strength="local_browser_control",
        supports="Local Chrome H3 workload controls expose workload-sensitive completion, retry, and session-attribution boundaries.",
        do_not_claim="Real Wi-Fi/cellular handover or single-session browser CM success.",
        next_gap="Use as workload prioritization basis for future controlled public/browser trials.",
    ),
    EvidenceItem(
        id="chrome-desktop-noniphone-media-local-refresh",
        chapter="6/11",
        category="browser-local-media-control",
        implementation="Chrome + quic-go local UDP rebinding proxy",
        evidence_doc="docs/results/chrome-desktop-noniphone-media-local-refresh-20260630.md",
        runner_or_tool="repro/quic-go-min-repro/scripts/run-chrome-h3-rebinding-proxy.sh",
        local_artifact_id="chrome-desktop-noniphone-media-drop3000-retry0-20260630",
        claim_strength="local_browser_positive_control",
        supports="A fresh Chrome desktop forced-H3 media run completed across local UDP rebinding with one target QUIC session, two server-observed remote tuples, qlog path validation, and NetLog target path challenge/response evidence.",
        do_not_claim="Public Wi-Fi/LTE handover, iPhone handover, or general browser CM deployment success.",
        next_gap="Run controlled-public page-ready media/upload/range handover once public origin and active path-change gates are open.",
    ),
    EvidenceItem(
        id="chrome-desktop-noniphone-musiclike-local-refresh",
        chapter="11",
        category="browser-local-music-control",
        implementation="Chrome + quic-go local UDP rebinding proxy",
        evidence_doc="docs/results/chrome-desktop-noniphone-musiclike-local-refresh-20260701.md",
        runner_or_tool="repro/quic-go-min-repro/scripts/run-chrome-h3-rebinding-proxy.sh",
        local_artifact_id="chrome-desktop-noniphone-musiclike-20260701-pair",
        claim_strength="local_browser_recovery_control",
        supports="Fresh Chrome desktop music-like segment rows reconfirm that a 6000ms local outage fails without segment retry but completes with one retry via multiple QUIC sessions.",
        do_not_claim="Music streaming is protected by single-session browser Connection Migration, public Wi-Fi/LTE handover, or transport-level continuity.",
        next_gap="Run controlled-public page-ready media/music handover once an H3-ready public origin and active path-change gate are available.",
    ),
    EvidenceItem(
        id="chrome-desktop-noniphone-buffered-media-local-refresh",
        chapter="11",
        category="browser-local-buffered-media-control",
        implementation="Chrome + quic-go local UDP rebinding proxy",
        evidence_doc="docs/results/chrome-desktop-noniphone-buffered-media-local-refresh-20260701.md",
        runner_or_tool="repro/quic-go-min-repro/scripts/run-chrome-h3-rebinding-proxy.sh",
        local_artifact_id="chrome-desktop-noniphone-buffered-media-20260701-pair",
        claim_strength="local_browser_qoe_control",
        supports="Fresh Chrome desktop buffered-media rows completed playback across a 6000ms local outage, but low/high buffer policies produced different rebuffer counts and both rows used multiple Chrome target QUIC sessions.",
        do_not_claim="Video playback was protected by single-session browser Connection Migration, public Wi-Fi/LTE handover, or zero-QoE-impact continuity.",
        next_gap="Run controlled-public page-ready buffered-media handover and report startup delay, rebuffer events, retry count, session count, and qlog path evidence together.",
    ),
    EvidenceItem(
        id="chrome-desktop-noniphone-range-local-refresh",
        chapter="6/9",
        category="browser-local-range-control",
        implementation="Chrome + quic-go local UDP rebinding proxy",
        evidence_doc="docs/results/chrome-desktop-noniphone-range-local-refresh-20260630.md",
        runner_or_tool="repro/quic-go-min-repro/scripts/run-chrome-h3-rebinding-proxy.sh",
        local_artifact_id="chrome-desktop-noniphone-range-20260630-pair",
        claim_strength="local_browser_positive_control",
        supports="Two fresh Chrome desktop forced-H3 byte-range runs completed a 1MiB range task without application retry across local UDP rebinding with one target QUIC session, two server-observed remote tuples, and qlog path validation.",
        do_not_claim="Public Wi-Fi/LTE handover, iPhone handover, or general browser CM deployment success.",
        next_gap="Run controlled-public page-ready byte-range handover once public origin and active path-change gates are open.",
    ),
    EvidenceItem(
        id="chrome-desktop-noniphone-upload-local-refresh",
        chapter="6/10",
        category="browser-local-upload-control",
        implementation="Chrome + quic-go local UDP rebinding proxy",
        evidence_doc="docs/results/chrome-desktop-noniphone-upload-local-refresh-20260630.md",
        runner_or_tool="repro/quic-go-min-repro/scripts/run-chrome-h3-rebinding-proxy.sh",
        local_artifact_id="chrome-desktop-noniphone-upload-drop3000-retry0-20260630",
        claim_strength="local_browser_positive_control",
        supports="A fresh Chrome desktop forced-H3 upload run completed without application retry while proxy packets crossed both upstream sockets and qlog/NetLog path validation was observed, even though request-level server remote tuple count stayed at one.",
        do_not_claim="Public Wi-Fi/LTE handover, iPhone handover, or request-log-only proof of packet-level rebinding.",
        next_gap="Run controlled-public page-ready upload handover once public origin and active path-change gates are open.",
    ),
    EvidenceItem(
        id="noniphone-workload-qoe-synthesis",
        chapter="9/10/11",
        category="workload-synthesis",
        implementation="Chrome + quic-go local workload CSV corpus",
        evidence_doc="docs/results/noniphone-workload-qoe-continuity-synthesis-20260701.md",
        runner_or_tool="tools/build_noniphone_workload_qoe_synthesis.py",
        local_artifact_id="noniphone-workload-qoe-continuity-synthesis-20260701",
        claim_strength="paper_synthesis",
        supports="Thirty-two normalized non-iPhone local Chrome workload rows show that range/download and upload have cleaner single-session local path-validation evidence, while buffered video and music-like segment completion must be framed with QoE, retry/reconnect, and session churn.",
        do_not_claim="Public Wi-Fi/LTE handover, CDN deployment continuity, or that all streaming workloads are protected by single-session browser Connection Migration.",
        next_gap="After an H3-ready public origin is available, run public range/upload trials first, then buffered and music-like streaming trials with QoE/session metrics.",
    ),
    EvidenceItem(
        id="controlled-public-origin-workload-deploy-packet",
        chapter="7/9/10/11",
        category="public-origin-deploy-plan",
        implementation="controlled public quic-go H3 origin",
        evidence_doc="docs/results/controlled-public-origin-workload-deploy-packet-20260701.md",
        runner_or_tool="tools/build_controlled_public_origin_deploy_packet.py",
        local_artifact_id="controlled-public-origin-workload-deploy-packet-20260701",
        claim_strength="run_plan",
        supports="The WebPKI + Alt-Svc H3 origin setup is connected to the non-iPhone public range, upload, buffered-video, and music-like workload trial packet.",
        do_not_claim="A public origin is currently running, any public workload has been executed, or browser Connection Migration succeeded.",
        next_gap="Open the public H3 origin gate, run the baseline, then execute the non-iPhone public workload trial packet.",
    ),
    EvidenceItem(
        id="noniphone-desktop-path-change-readiness",
        chapter="7/9/10/11",
        category="desktop-path-readiness",
        implementation="macOS Chrome desktop path-change gate",
        evidence_doc="docs/results/noniphone-desktop-path-change-readiness-20260701.md",
        runner_or_tool="tools/build_noniphone_desktop_path_change_readiness.py",
        local_artifact_id="noniphone-desktop-path-change-readiness-20260701",
        claim_strength="readiness_blocked",
        supports="The current host has no active non-iPhone secondary desktop path; iPhone latent failover and Android candidates are excluded from the desktop public workload gate.",
        do_not_claim="A desktop active path-change command is ready, any public workload has been executed, or browser Connection Migration succeeded.",
        next_gap="Connect or enable a non-iPhone secondary path such as Ethernet or USB LAN, then rerun the readiness packet before setting NETWORK_CHANGE_CMD.",
    ),
    EvidenceItem(
        id="noniphone-public-workload-trial-packet",
        chapter="9/10/11",
        category="public-trial-plan",
        implementation="Chrome controlled-public workload protocol",
        evidence_doc="docs/results/noniphone-public-workload-trial-packet-20260701.md",
        runner_or_tool="tools/build_noniphone_public_workload_trial_packet.py",
        local_artifact_id="noniphone-public-workload-trial-packet-20260701",
        claim_strength="run_plan",
        supports="The next non-iPhone controlled-public Chrome workload order, command templates, and strong CM acceptance gates are fixed for range, upload, buffered video, and music-like segment trials.",
        do_not_claim="Any public workload has been executed or that browser Connection Migration succeeded.",
        next_gap="Open the H3 public-origin and desktop path-change gates, then execute the packet in order and classify each row.",
    ),
    EvidenceItem(
        id="noniphone-claim-readiness-dashboard",
        chapter="12",
        category="claim-readiness-synthesis",
        implementation="cross-layer evidence corpus",
        evidence_doc="docs/results/noniphone-claim-readiness-dashboard-20260701.md",
        runner_or_tool="tools/build_noniphone_claim_readiness_dashboard.py",
        local_artifact_id="noniphone-claim-readiness-dashboard-20260701",
        claim_strength="paper_synthesis",
        supports="Current evidence can be separated into paper-ready maturity/local-QoE claims and blocked public-browser/AWS/Safari claims without relying on raw private artifacts.",
        do_not_claim="New runtime evidence, public Chrome Connection Migration success, live AWS NLB+s2n success, or Safari handover success.",
        next_gap="Use the dashboard as the professor-facing decision table, then open AWS credentials or public-origin plus desktop-path gates for stronger positive evidence.",
    ),
    EvidenceItem(
        id="noniphone-professor-decision-packet",
        chapter="12",
        category="professor-decision-synthesis",
        implementation="cross-layer evidence corpus",
        evidence_doc="docs/results/noniphone-professor-decision-packet-20260701.md",
        runner_or_tool="tools/build_noniphone_professor_decision_packet.py",
        local_artifact_id="noniphone-professor-decision-packet-20260701",
        claim_strength="paper_synthesis",
        supports="A Korean professor-facing decision packet that separates recommended paper scope, optional positive-result gates, blocked claims, and questions for the next research meeting.",
        do_not_claim="New runtime evidence, final professor approval, public browser CM success, live AWS+s2n success, or Safari handover success.",
        next_gap="Use in the professor meeting to choose between conservative maturity/gap paper scope and opening AWS/public-browser gates for positive results.",
    ),
    EvidenceItem(
        id="noniphone-reviewer-risk-audit",
        chapter="12",
        category="reviewer-risk-synthesis",
        implementation="cross-layer evidence corpus",
        evidence_doc="docs/results/noniphone-reviewer-risk-audit-20260701.md",
        runner_or_tool="tools/build_noniphone_reviewer_risk_audit.py",
        local_artifact_id="noniphone-reviewer-risk-audit-20260701",
        claim_strength="paper_synthesis",
        supports="A reviewer-facing validity audit that identifies critical overclaim risks, external-validity gaps, AWS/browser/Safari claim boundaries, and defensive wording for the current paper scope.",
        do_not_claim="New runtime evidence, reviewer acceptance, public browser CM success, live AWS+s2n success, or Safari handover success.",
        next_gap="Use the audit to revise the paper abstract/introduction/method wording before deciding whether external positive-result gates must be opened.",
    ),
    EvidenceItem(
        id="noniphone-paper-wording-guard",
        chapter="12",
        category="paper-wording-synthesis",
        implementation="cross-layer evidence corpus",
        evidence_doc="docs/results/noniphone-paper-wording-guard-20260701.md",
        runner_or_tool="tools/build_noniphone_paper_wording_guard.py",
        local_artifact_id="noniphone-paper-wording-guard-20260701",
        claim_strength="paper_synthesis",
        supports="A bilingual paper wording guard that maps reviewer risks to safe abstract, introduction, method, results, limitations, and artifact-policy wording.",
        do_not_claim="New runtime evidence, final paper acceptance, public browser CM success, live AWS+s2n success, or Safari handover success.",
        next_gap="Use the wording guard while drafting the paper, especially before writing guarantee, mobile, browser, AWS, and streaming claims.",
    ),
    EvidenceItem(
        id="noniphone-paper-section-scaffold",
        chapter="12",
        category="paper-section-synthesis",
        implementation="cross-layer evidence corpus",
        evidence_doc="docs/results/noniphone-paper-section-scaffold-20260701.md",
        runner_or_tool="tools/build_noniphone_paper_section_scaffold.py",
        local_artifact_id="noniphone-paper-section-scaffold-20260701",
        claim_strength="paper_synthesis",
        supports="A paper-section scaffold that maps sanitized evidence and bilingual wording guard rules into abstract, introduction, method, results, and limitations sections.",
        do_not_claim="New runtime evidence, final paper text, public browser CM success, live AWS+s2n success, or Safari handover success.",
        next_gap="Use the scaffold to draft the conservative maturity/gap paper or revise it after external positive-result gates open.",
    ),
    EvidenceItem(
        id="non-quicgo-implementation-findings",
        chapter="1",
        category="implementation-synthesis",
        implementation="implementation survey excluding quic-go",
        evidence_doc="docs/results/non-quicgo-implementation-findings-20260701.md",
        runner_or_tool="tools/build_non_quicgo_implementation_findings.py",
        local_artifact_id="non-quicgo-implementation-findings-20260701",
        claim_strength="implementation_synthesis",
        supports="A professor-facing synthesis of what was verified outside quic-go, separating broad cross-stack evidence, server/app demos, focused partial positives, readiness blockers, and the HAProxy negative control.",
        do_not_claim="New runtime evidence beyond the referenced artifacts, equal maturity across all stacks, browser handover success, or managed deployment continuity.",
        next_gap="Use this synthesis when explaining why quic-go is the deepest positive control while non-quic-go evidence still rejects a pure implementation-absence explanation.",
    ),
    EvidenceItem(
        id="non-quicgo-execution-depth-audit",
        chapter="1",
        category="implementation-depth-boundary",
        implementation="implementation survey excluding quic-go",
        evidence_doc="docs/results/non-quicgo-execution-depth-audit-20260701.md",
        runner_or_tool="tools/build_non_quicgo_execution_depth_audit.py",
        local_artifact_id="non-quicgo-execution-depth-audit-20260701",
        claim_strength="implementation_depth_synthesis",
        supports="A row-level explanation of why quic-go has the deepest controlled AddPath/Probe/Switch evidence while non-quic-go stacks still contribute test-suite, runtime, source, deployment-readiness, and negative-control evidence.",
        do_not_claim="New runtime evidence, equal active migration control across all stacks, browser handover success, or managed deployment continuity.",
        next_gap="Use the remaining-deepening candidates to decide whether AWS NLB+s2n, mvfst Linux build, CloudFront edge, XQUIC Linux, quicly full e2e, or Chrome/Cronet runtime rows are worth opening next.",
    ),
    EvidenceItem(
        id="msquic-migration-api-boundary-audit",
        chapter="1",
        category="implementation-api-boundary",
        implementation="MsQuic",
        evidence_doc="docs/results/msquic-migration-api-boundary-audit-20260701.md",
        runner_or_tool="tools/build_msquic_migration_api_boundary_audit.py",
        local_artifact_id="msquic-migration-api-boundary-audit-20260701",
        claim_strength="source_linked_api_boundary",
        supports="MsQuic exposes MigrationEnabled, address-change events, constrained QUIC_PARAM_CONN_LOCAL_ADDRESS control, and NAT rebinding tests while documenting a QUIC-aware load-balancing boundary.",
        do_not_claim="quic-go-style AddPath/Probe/Switch control, managed-LB continuity, browser handover success, or new runtime payload continuity beyond existing MsQuic tests.",
        next_gap="Build a focused MsQuic runtime harness only if reviewers require a second production-oriented active-control artifact.",
    ),
]


def path_exists(path: str) -> bool:
    return bool(path) and Path(path).exists()


def build_bundle() -> dict[str, Any]:
    items = []
    for item in EVIDENCE_ITEMS:
        record = asdict(item)
        record["evidence_doc_exists"] = path_exists(item.evidence_doc)
        record["runner_or_tool_exists"] = path_exists(item.runner_or_tool)
        record["public_safe_note"] = "No raw qlog, keylog, pcap, private host, credential, account ID, or device identifier is included."
        items.append(record)

    return {
        "generated": utc_date_iso(),
        "public_safe": True,
        "item_count": len(items),
        "claim_strength_counts": dict(sorted(Counter(item["claim_strength"] for item in items).items())),
        "category_counts": dict(sorted(Counter(item["category"] for item in items).items())),
        "missing_evidence_docs": [item["id"] for item in items if not item["evidence_doc_exists"]],
        "missing_runners_or_tools": [item["id"] for item in items if item["runner_or_tool"] and not item["runner_or_tool_exists"]],
        "items": items,
    }


def emit_markdown(bundle: dict[str, Any]) -> str:
    lines = [
        "# Sanitized Evidence Bundle",
        "",
        f"Generated: `{bundle['generated']}`",
        "",
        "This bundle is public-safe. It maps committed result documents and reproducible runners/tools to the claim each artifact can support and the claim it must not be used to support.",
        "",
        "It intentionally does not copy raw qlogs, keylogs, pcaps, NetLogs, private hostnames, account IDs, device IDs, public IPs, or credentials.",
        "",
        "## Summary",
        "",
        "| field | value |",
        "| --- | --- |",
        f"| item count | `{bundle['item_count']}` |",
        f"| claim strength counts | `{bundle['claim_strength_counts']}` |",
        f"| category counts | `{bundle['category_counts']}` |",
        f"| missing evidence docs | `{bundle['missing_evidence_docs']}` |",
        f"| missing runners/tools | `{bundle['missing_runners_or_tools']}` |",
        "",
        "## Evidence Items",
        "",
        "| id | implementation | strength | evidence doc | runner/tool | supports | do not claim | next gap |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in bundle["items"]:
        evidence_status = "yes" if item["evidence_doc_exists"] else "missing"
        runner_status = "yes" if item["runner_or_tool_exists"] else "missing"
        evidence = f"`{item['evidence_doc']}` ({evidence_status})"
        runner = f"`{item['runner_or_tool']}` ({runner_status})" if item["runner_or_tool"] else "-"
        lines.append(
            "| {id} | {implementation} | `{claim_strength}` | {evidence} | {runner} | {supports} | {do_not_claim} | {next_gap} |".format(
                id=f"`{item['id']}`",
                implementation=item["implementation"],
                claim_strength=item["claim_strength"],
                evidence=evidence,
                runner=runner,
                supports=item["supports"],
                do_not_claim=item["do_not_claim"],
                next_gap=item["next_gap"],
            )
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- This bundle is an evidence-to-claim map, not a raw artifact archive.",
            "- A strong implementation positive control does not imply browser or managed CDN continuity.",
            "- Negative controls are first-class evidence because they prevent overclaiming HTTP/3 support as Connection Migration support.",
            "- Readiness-blocked items are useful because they record why a live claim is not yet available.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_outputs(output: Path, json_output: Path, bundle: dict[str, Any]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    json_output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(emit_markdown(bundle), encoding="utf-8")
    json_output.write_text(json.dumps(bundle, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--json-output", default=DEFAULT_JSON_OUTPUT)
    args = parser.parse_args()

    bundle = build_bundle()
    write_outputs(Path(args.output), Path(args.json_output), bundle)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
